version: '3.8'

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: WpSecure2026!Rand#K8s
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: WordPr2026#Pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress-net

  wordpress:
    image: wordpress:6.5.3-php8.2-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: WordPr2026#Pass
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-net
    depends_on:
      - mysql

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress-net:
    driver: bridge
